### ISSUE TITLE
Some problem with Vovney

### ISSUE THREAD

**Issue by masyanru** [brainfair/k8s-in-azure#1]
Hello,
good repo with do all respect, I tried everything and went through all the steps, even tried to deploy this application, but it seems to me that Vovney is still badly motivated. It's possible that the problem is with my ingress controller, but I'm not sure.

Thx for your help.

**Comment by brainfair** [comment]
Hello,
I am sorry that you have encountered this problem. Send a full debug log of the problem and we will try to improve Vovney motivation app, but maybe nothing will help here.

**Comment by brainfair** [comment]
by inactivity
